clone_depth: 1

environment:
    matrix:
        # - MINGW_VERSION: mingw32
        #   ARCH: i686
        - MINGW_VERSION: mingw64
          ARCH: x86_64

matrix:
    fast_finish: true

build_script:
    - cd C:\projects\scopy-mingw-build-deps
    - C:\msys64\usr\bin\bash build.sh
    - appveyor PushArtifact c:\projects\scopy-mingw-build-deps\dependencies.txt
    - appveyor PushArtifact c:\projects\scopy-mingw-build-deps\scopy-%MINGW_VERSION%-build-deps.tar.xz
